language: python

matrix:
  include:
    # mubench.cli & mubench.utils
    - language: java
      jdk: oraclejdk8
      script:
        - mvn verify -f mubench.cli/pom.xml
        - mvn verify -f mubench.utils/pom.xml
    
    # mubench.pipeline
    - language: python
      python: 3.5
      install:
        - pip install -r mubench.pipeline/requirements.txt
      script:
        - nosetests -w mubench.pipeline
        - python ./mubench.pipeline/benchmark.py run ex1 DemoDetector --only synthetic_survey

    # mubench.reviewsite
    - language: php
      php: 7.0
      script:
        - cd mubench.reviewsite
        - ./configure.sh
        - phpunit --bootstrap vendor/autoload.php tests/
